name: Python Master Workflow
on:
  push:
    branches:
      - 'main'
jobs:
  codecov:
    name: Codecov Workflow
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: 3.8
      - name: Generate coverage report
        run: |
          pip install pytest
          pip install flask
          pip install pytest-cov
          pip install flask_bootstrap
          pytest --cov=./ --cov-report=xml tests.py
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: f199820c-05ae-451b-9654-821ad9c47c14
          file: ./coverage.xml
          flags: unittests
